// Code generated by go-swagger; DO NOT EDIT.

package upload_and_create_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostV1UploadFilesOKCode is the HTTP code returned for type PostV1UploadFilesOK
const PostV1UploadFilesOKCode int = 200

/*PostV1UploadFilesOK OK

swagger:response postV1UploadFilesOK
*/
type PostV1UploadFilesOK struct {
}

// NewPostV1UploadFilesOK creates PostV1UploadFilesOK with default headers values
func NewPostV1UploadFilesOK() *PostV1UploadFilesOK {

	return &PostV1UploadFilesOK{}
}

// WriteResponse to the client
func (o *PostV1UploadFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
