// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Bulk Issuance API",
    "title": "Bulk Issuance",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/bulk/sample/{schemaName}": {
      "get": {
        "security": [],
        "produces": [
          "multipart/form-data"
        ],
        "tags": [
          "sampleTemplate"
        ],
        "summary": "get sample template",
        "parameters": [
          {
            "type": "string",
            "description": "schema name",
            "name": "schemaName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SampleTemplateResponse"
            }
          }
        }
      }
    },
    "/v1/bulk/uploadedFiles": {
      "get": {
        "security": [],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "uploadedFiles"
        ],
        "summary": "get uploaded files",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/v1/download/{fileName}": {
      "get": {
        "security": [],
        "produces": [
          "multipart/form-data"
        ],
        "tags": [
          "downloadFileReport"
        ],
        "summary": "download the success and error report of file uploaded",
        "parameters": [
          {
            "type": "string",
            "description": "File name",
            "name": "fileName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/FileDownload"
            }
          }
        }
      }
    },
    "/v1/uploadFiles": {
      "post": {
        "security": [],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "uploadAndCreateRecords"
        ],
        "summary": "upload the file and create records",
        "parameters": [
          {
            "type": "file",
            "description": "Certification data in the form of csv",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "FileDownload": {
      "type": "object"
    },
    "SampleTemplateResponse": {
      "type": "object"
    },
    "UploadedFiles": {
      "type": "object"
    }
  },
  "security": [
    {
      "hasRole": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Bulk Issuance API",
    "title": "Bulk Issuance",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/bulk/sample/{schemaName}": {
      "get": {
        "security": [],
        "produces": [
          "multipart/form-data"
        ],
        "tags": [
          "sampleTemplate"
        ],
        "summary": "get sample template",
        "parameters": [
          {
            "type": "string",
            "description": "schema name",
            "name": "schemaName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SampleTemplateResponse"
            }
          }
        }
      }
    },
    "/v1/bulk/uploadedFiles": {
      "get": {
        "security": [],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "uploadedFiles"
        ],
        "summary": "get uploaded files",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/v1/download/{fileName}": {
      "get": {
        "security": [],
        "produces": [
          "multipart/form-data"
        ],
        "tags": [
          "downloadFileReport"
        ],
        "summary": "download the success and error report of file uploaded",
        "parameters": [
          {
            "type": "string",
            "description": "File name",
            "name": "fileName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/FileDownload"
            }
          }
        }
      }
    },
    "/v1/uploadFiles": {
      "post": {
        "security": [],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "uploadAndCreateRecords"
        ],
        "summary": "upload the file and create records",
        "parameters": [
          {
            "type": "file",
            "description": "Certification data in the form of csv",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "FileDownload": {
      "type": "object"
    },
    "SampleTemplateResponse": {
      "type": "object"
    },
    "UploadedFiles": {
      "type": "object"
    }
  },
  "security": [
    {
      "hasRole": []
    }
  ]
}`))
}
